name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Docker image
        run: |
          docker build -t node-todo-app .

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag Docker image
        run: |
          docker tag node-todo-app:latest 298859898743.dkr.ecr.us-east-1.amazonaws.com/node-todo-app:latest

      - name: Push Docker image
        run: |
          docker push 298859898743.dkr.ecr.us-east-1.amazonaws.com/node-todo-app:latest

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v1
        with:
          version: '1.24.0'

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name eks-cluster --region us-east-1

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
